### ISSUE TITLE
issue with display of regions tab in Coteries table?

### ISSUE THREAD

**Issue by schellenb** [sfu-dhil/mvm#109] opened 2021-02-05 18:26 UTC
when I go the Coteries tab in Explore and select a coterie connected to a region (e.g. Burroughs-Crowfoot), the People and Manuscripts tabs produce clear results, but I don't understand what I'm seeing under the Regions tab - I seem to be getting the entire listing for "Norfolk" and "Norwich," including manuscripts and print sources that have nothing to do with this coterie.

**Comment by ubermichael** [comment] 2021-02-05 18:45
This is Joey's issue, so reassigning to him.

**Comment by angelawachowich** [comment] 2021-02-05 19:31
Just to clarify, Betty, would you prefer to just see the Regions associated with the Coterie without seeing anything else about them? 
If the display is to stay the way it is now instead, would we be able to see other Coteries associated with the Regions listed, as well? 
I have no preference, just thought I'd ask.

**Comment by joeytakeda** [comment] 2021-02-05 19:42
Right now, the Regions tab for a given coterie displays the subset of the regions index that applies to the coterie. The issue is that there isn't much to display in the region tab: unlike, say, the contributors or features tabs in manuscripts, there's nothing beyond the name of the region that we can display, but just displaying a list of region names seems sort of bathetic since the expectation from other contexts is that a tab contains a fairly significant amount of information. So the table provides a bit more information about the region (making the click a bit more worthwhile), but I can see how it may give the impression that the print source and manuscript count has something to do with the coterie.

So simplest solution would be to remove the last two columns for the region display in the REGIONS tab for the coteries; another solution could be to place the regions above the fleuron as a simple list (identical to how they appear for print sources). Did you have any other ideas of how you'd like the regions to display?

**Comment by schellenb** [comment] 2021-02-05 22:57
HI, If regions went above the fleuron as a list, presumably each of those regions could be clicked to find out anything else associated with it (print sources, mss, possible other coteries). To me this would convey a clearer message than having the print sources and mss show up, as now, on a table that is devoted to this coterie.

**Closed** 2021-02-22 18:52 UTC
Labels: bug
